ARG GO_VERSION
FROM golang:${GO_VERSION} AS downloader

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@v1.20.2
COPY go.mod .
COPY go.sum .
# It is done only once unless go.mod has been changed
RUN go mod download

FROM downloader AS builder

WORKDIR /app
COPY pkg /app/pkg
COPY tests /app/tests
COPY --from=downloader /go/bin/dlv /bin/

RUN go test -c -gcflags "all=-N -l" -ldflags "-extldflags '-static'" -o /usr/bin/tests /app/tests

ENTRYPOINT ["/bin/dlv", "--listen=:2345", "--headless=true", "--api-version=2", "exec", "/usr/bin/tests", "--"]
# By default test is verbose, but it can be changed when container is launched.
CMD ["-test.v"]
